<?php
function agreement_login_user($op, &$edit, &$account, $category = NULL)
{
    global $base_url;
    $isPopup = check_agreement();
    drupal_add_js(drupal_get_path('module', 'agreement_login') . '/js/popup.js');
    drupal_add_js(
        array(
            'baseUrl' => $base_url
        ),
        'setting'
    );
    drupal_add_js(
        array(
            'isPopup' => $isPopup
        ),
        'setting'
    );
    if ($op == 'login') {
        if (isset($_GET['destination'])) {
            unset($_GET['destination']);
            unset($_REQUEST['destination']);
        }

        if ($isPopup) {
            drupal_goto('/node/4');
        }
        drupal_goto('/node/1'); //welcome page.
    }
}
function check_agreement()
{
    global $user;
    $expried_date = db_fetch_object(db_query("SELECT * FROM {agreement_login} WHERE uid = $user->uid"))->expired_date;
    if ($expried_date === fase || time() > $expried_date)
        return true;
    return false;
}
function agreement_login_menu()
{
    $items = array();
    // Create a path to send our AJAX request to.
    $items['mymodule_ajax'] = array(
        'page callback' => 'mymodule_ajax_callback',
        'access arguments' => array('access example ajax'),
        'type' => MENU_CALLBACK,
        'access callback' => TRUE
    );

    return $items;
}

function mymodule_ajax_callback()
{
    global $user;
    $nextYear =  strtotime("next year");
    $r = db_query("SELECT * FROM {agreement_login} WHERE uid = $user->uid");
    if ($r->num_rows == 0) { //first login
        db_query("INSERT INTO {agreement_login} (uid, expired_date)  VALUES (%d, '%d')", $user->uid, $nextYear);
    } else { // after one year update to next year
        db_query("UPDATE {agreement_login} SET expired_date= $nextYear WHERE uid= $user->uid");
    }
    setcookie('isPopup', 1, time() + (86400 * 30), "/");
}
